export const playersFakeList = [
  {
    dateOfBirth: '1999-10-23',
    matchAge: 20.9,
    height: 191,
    weight: 88,
    firstname: 'Nick',
    surname: 'Coffield',
    positions: {
      selected: {
        id: 4143,
        code: 'rule_subbed',
        name: 'Back Pocket',
      },
      season: {
        id: 3200,
        code: 'GD',
        name: 'Gen Def',
      },
    },
    jumperNumber: 1,
    displayName: 'N.Coffield',
    fullname: 'Nick Coffield',
    personId: 1005717,
    disabled: true,
  },
  {
    dateOfBirth: '1995-03-15',
    matchAge: 25.5,
    height: 182,
    weight: 79,
    firstname: 'Zak',
    surname: 'Jones',
    positions: {
      selected: {
        id: 4150,
        code: 'HFF',
        name: 'Half Forward Flank',
      },
      season: {
        id: 2000,
        code: 'M',
        name: 'Mid',
      },
    },
    jumperNumber: 3,
    displayName: 'Z.Jones',
    fullname: 'Zak Jones',
    personId: 991988,
  },
  {
    dateOfBirth: '1993-05-07',
    matchAge: 27.3,
    height: 187,
    weight: 85,
    firstname: 'Sebastian',
    surname: 'Ross',
    positions: {
      selected: {
        id: 4148,
        code: 'OB',
        name: 'On Ball',
      },
      season: {
        id: 2000,
        code: 'M',
        name: 'Mid',
      },
    },
    jumperNumber: 6,
    displayName: 'S.Ross',
    fullname: 'Sebastian Ross',
    personId: 293846,
  },
  {
    dateOfBirth: '1993-07-09',
    matchAge: 27.2,
    height: 182,
    weight: 81,
    firstname: 'Bradley',
    surname: 'Hill',
    positions: {
      selected: {
        id: 4147,
        code: 'W',
        name: 'Wing',
      },
      season: {
        id: 4467,
        code: 'W',
        name: 'Wing',
      },
    },
    jumperNumber: 8,
    displayName: 'B.Hill',
    fullname: 'Bradley Hill',
    personId: 295584,
  },
  {
    dateOfBirth: '1995-12-13',
    matchAge: 24.7,
    height: 187,
    weight: 88,
    firstname: 'Jack',
    surname: 'Steele',
    positions: {
      selected: {
        id: 4157,
        code: 'rule_med',
        name: 'On Ball',
      },
      season: {
        id: 2000,
        code: 'M',
        name: 'Mid',
      },
    },
    jumperNumber: 9,
    displayName: 'J.Steele',
    fullname: 'Jack Steele',
    personId: 296205,
    disabled: true,
  },
  {
    dateOfBirth: '1999-03-26',
    matchAge: 21.5,
    height: 186,
    weight: 80,
    firstname: 'Hunter',
    surname: 'Clark',
    positions: {
      selected: {
        id: 4159,
        code: 'INT',
        name: 'Interchange',
      },
      season: {
        id: 3200,
        code: 'GD',
        name: 'Gen Def',
      },
    },
    jumperNumber: 11,
    displayName: 'H.Clark',
    fullname: 'Hunter Clark',
    personId: 1002264,
  },
  {
    dateOfBirth: '1996-08-13',
    matchAge: 24.1,
    height: 174,
    weight: 72,
    firstname: 'Jack',
    surname: 'Lonie',
    positions: {
      selected: {
        id: 4158,
        code: 'OB',
        name: 'On Ball',
      },
      season: {
        id: 1200,
        code: 'GF',
        name: 'Gen Fwd',
      },
    },
    jumperNumber: 13,
    displayName: 'J.Lonie',
    fullname: 'Jack Lonie',
    personId: 992000,
  },
  {
    dateOfBirth: '1988-06-23',
    matchAge: 32.2,
    height: 183,
    weight: 79,
    firstname: 'Jarryn',
    surname: 'Geary',
    positions: {
      selected: {
        id: 4141,
        code: 'BP',
        name: 'Back Pocket',
      },
      season: {
        id: 3200,
        code: 'GD',
        name: 'Gen Def',
      },
    },
    jumperNumber: 14,
    displayName: 'J.Geary',
    fullname: 'Jarryn Geary',
    personId: 260113,
  },
  {
    dateOfBirth: '1995-08-18',
    matchAge: 25.1,
    height: 185,
    weight: 80,
    firstname: 'Jack',
    surname: 'Billings',
    positions: {
      selected: {
        id: 4149,
        code: 'W',
        name: 'Wing',
      },
      season: {
        id: 4467,
        code: 'W',
        name: 'Wing',
      },
    },
    jumperNumber: 15,
    displayName: 'J.Billings',
    fullname: 'Jack Billings',
    personId: 296351,
  },
  {
    dateOfBirth: '1996-06-03',
    matchAge: 24.3,
    height: 182,
    weight: 81,
    firstname: 'Dan',
    surname: 'Butler',
    positions: {
      selected: {
        id: 4152,
        code: 'HFF',
        name: 'Half Forward Flank',
      },
      season: {
        id: 1200,
        code: 'GF',
        name: 'Gen Fwd',
      },
    },
    jumperNumber: 16,
    displayName: 'D.Butler',
    fullname: 'Dan Butler',
    personId: 992374,
  },
  {
    dateOfBirth: '1988-03-14',
    matchAge: 32.5,
    height: 197,
    weight: 96,
    firstname: 'Paddy',
    surname: 'Ryder',
    positions: {
      selected: {
        id: 4156,
        code: 'RK',
        name: 'Ruck',
      },
      season: {
        id: 4000,
        code: 'RK',
        name: 'Ruck',
      },
    },
    jumperNumber: 18,
    displayName: 'P.Ryder',
    fullname: 'Paddy Ryder',
    personId: 250267,
  },
  {
    dateOfBirth: '1995-11-24',
    matchAge: 24.8,
    height: 201,
    weight: 105,
    firstname: 'Rowan',
    surname: 'Marshall',
    positions: {
      selected: {
        id: 4154,
        code: 'FF',
        name: 'Full Forward',
      },
      season: {
        id: 4000,
        code: 'RK',
        name: 'Ruck',
      },
    },
    jumperNumber: 19,
    displayName: 'R.Marshall',
    fullname: 'Rowan Marshall',
    personId: 992468,
  },
  {
    dateOfBirth: '1996-03-25',
    matchAge: 24.5,
    height: 199,
    weight: 94,
    firstname: 'Dougal',
    surname: 'Howard',
    positions: {
      selected: {
        id: 4145,
        code: 'CHB',
        name: 'Centre Half Back',
      },
      season: {
        id: 3100,
        code: 'KD',
        name: 'Key Def',
      },
    },
    jumperNumber: 20,
    displayName: 'D.Howard',
    fullname: 'Dougal Howard',
    personId: 993480,
  },
  {
    dateOfBirth: '1997-08-21',
    matchAge: 23,
    height: 183,
    weight: 81,
    firstname: 'Ben',
    surname: 'Long',
    positions: {
      selected: {
        id: 4146,
        code: 'HBF',
        name: 'Half Back Flank',
      },
      season: {
        id: 3200,
        code: 'GD',
        name: 'Gen Def',
      },
    },
    jumperNumber: 21,
    displayName: 'B.Long',
    fullname: 'Ben Long',
    personId: 993917,
  },
  {
    dateOfBirth: '1994-02-24',
    matchAge: 26.5,
    height: 181,
    weight: 83,
    firstname: 'Dean',
    surname: 'Kent',
    positions: {
      selected: {
        id: 4160,
        code: 'INT',
        name: 'Interchange',
      },
      season: {
        id: 1200,
        code: 'GF',
        name: 'Gen Fwd',
      },
    },
    jumperNumber: 25,
    displayName: 'D.Kent',
    fullname: 'Dean Kent',
    personId: 294570,
  },
  {
    dateOfBirth: '1998-09-01',
    matchAge: 22,
    height: 193,
    weight: 92,
    firstname: 'Josh',
    surname: 'Battle',
    positions: {
      selected: {
        id: 4155,
        code: 'FP',
        name: 'Forward Pocket',
      },
      season: {
        id: 2010,
        code: 'MF',
        name: 'Mid-Fwd',
      },
    },
    jumperNumber: 26,
    displayName: 'J.Battle',
    fullname: 'Josh Battle',
    personId: 998134,
  },
  {
    dateOfBirth: '1991-06-25',
    matchAge: 29.2,
    height: 202,
    weight: 102,
    firstname: 'Ryan',
    surname: 'Abbott',
    positions: {
      selected: {
        id: 4151,
        code: 'CHF',
        name: 'Centre Half Forward',
      },
      season: {
        id: 4000,
        code: 'RK',
        name: 'Ruck',
      },
    },
    jumperNumber: 27,
    displayName: 'R.Abbott',
    fullname: 'Ryan Abbott',
    personId: 1005530,
  },
  {
    dateOfBirth: '1998-03-29',
    matchAge: 22.4,
    height: 189,
    weight: 83,
    firstname: 'Ed',
    surname: 'Phillips',
    positions: {
      selected: {
        id: 4161,
        code: 'INT',
        name: 'Interchange',
      },
      season: {
        id: 4467,
        code: 'W',
        name: 'Wing',
      },
    },
    jumperNumber: 30,
    displayName: 'E.Phillips',
    fullname: 'Ed Phillips',
    personId: 1002213,
  },
  {
    dateOfBirth: '1998-10-19',
    matchAge: 21.9,
    height: 186,
    weight: 81,
    firstname: 'Ben',
    surname: 'Paton',
    positions: {
      selected: {
        id: 4144,
        code: 'HBF',
        name: 'Half Back Flank',
      },
      season: {
        id: 3200,
        code: 'GD',
        name: 'Gen Def',
      },
    },
    jumperNumber: 33,
    displayName: 'B.Paton',
    fullname: 'Ben Paton',
    personId: 1004985,
  },
  {
    dateOfBirth: '1995-02-12',
    matchAge: 25.6,
    height: 181,
    weight: 82,
    firstname: 'Jack',
    surname: 'Sinclair',
    positions: {
      selected: {
        id: 4162,
        code: 'INT',
        name: 'Interchange',
      },
      season: {
        id: 2000,
        code: 'M',
        name: 'Mid',
      },
    },
    jumperNumber: 35,
    displayName: 'J.Sinclair',
    fullname: 'Jack Sinclair',
    personId: 994389,
  },
  {
    dateOfBirth: '1995-10-17',
    matchAge: 24.9,
    height: 194,
    weight: 89,
    firstname: 'Jonathon',
    surname: 'Marsh',
    positions: {
      selected: {
        id: 4153,
        code: 'FFP',
        name: 'Forward Pocket',
      },
      season: {
        id: 1100,
        code: 'KF',
        name: 'Key Fwd',
      },
    },
    jumperNumber: 43,
    displayName: 'J.Marsh',
    fullname: 'Jonathon Marsh',
    personId: 990548,
  },
  {
    dateOfBirth: '1996-03-10',
    matchAge: 24.5,
    height: 191,
    weight: 87,
    firstname: 'Callum',
    surname: 'Wilkie',
    positions: {
      selected: {
        id: 4142,
        code: 'FB',
        name: 'Full Back',
      },
      season: {
        id: 3200,
        code: 'GD',
        name: 'Gen Def',
      },
    },
    jumperNumber: 44,
    displayName: 'C.Wilkie',
    fullname: 'Callum Wilkie',
    personId: 296422,
  },
];

export const bloodRulePlayers = [
  {
    personId: 296422,
    quarter: 1,
    realTime: 0,
    quarterTime: 1,
    time: 0,
    player: {}
  },
  {
    personId: 1005717,
    quarter: 1,
    realTime: 0,
    quarterTime: 1,
    time: 0,
    player: {}
  },
];

export const concussRulePlayers = {};

export const medicalSubPlayers = [
  {
    personId: 990548,
    quarter: 1,
    gameTime: '',
    realTime: '',
    timerId: 1,
  },
];
export const medicalRulePlayers = [
  {
    personId: 994389,
    quarter: 1,
    gameTime: '',
    realTime: '',
    timerId: 1,
  },
];
